// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvRgZTUUIC0Bh-NNPA98EO5sXV1BKb-s4',
    appId: '1:78015902895:web:fd90ee48909f70b4df105a',
    messagingSenderId: '78015902895',
    projectId: 'sihbruteforce',
    authDomain: 'sihbruteforce.firebaseapp.com',
    storageBucket: 'sihbruteforce.firebasestorage.app',
    measurementId: 'G-5H6GJRLDNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHiOALZSq_wbZc2syTaw3mlhlb87s9Rso',
    appId: '1:78015902895:android:4f44a661fd2521e6df105a',
    messagingSenderId: '78015902895',
    projectId: 'sihbruteforce',
    storageBucket: 'sihbruteforce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN6HE3_tjn0HeoD5nBajAHYwaLJEApr-0',
    appId: '1:78015902895:ios:ccfddb1ec96e3e20df105a',
    messagingSenderId: '78015902895',
    projectId: 'sihbruteforce',
    storageBucket: 'sihbruteforce.firebasestorage.app',
    iosClientId: '78015902895-drdoa7f4qj6djlqkqm7mnc5u8ktoss80.apps.googleusercontent.com',
    iosBundleId: 'com.example.sih2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN6HE3_tjn0HeoD5nBajAHYwaLJEApr-0',
    appId: '1:78015902895:ios:ccfddb1ec96e3e20df105a',
    messagingSenderId: '78015902895',
    projectId: 'sihbruteforce',
    storageBucket: 'sihbruteforce.firebasestorage.app',
    iosClientId: '78015902895-drdoa7f4qj6djlqkqm7mnc5u8ktoss80.apps.googleusercontent.com',
    iosBundleId: 'com.example.sih2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvRgZTUUIC0Bh-NNPA98EO5sXV1BKb-s4',
    appId: '1:78015902895:web:7544271a26990507df105a',
    messagingSenderId: '78015902895',
    projectId: 'sihbruteforce',
    authDomain: 'sihbruteforce.firebaseapp.com',
    storageBucket: 'sihbruteforce.firebasestorage.app',
    measurementId: 'G-6RG6LMQDGZ',
  );
}
